from lammps import lammps
import lammps_logfile
from mpi4py import MPI
import matplotlib.pyplot as plt
import time
import glob
import os
from PIL import Image

# Initialize LAMMPS instance
log_filename = "log.lj_restart"
lmp = lammps(cmdargs=["-log", log_filename, "-screen", "none"])
if MPI.COMM_WORLD.Get_rank() == 0:
    print(f"LAMMPS Version Date Code: {lmp.version()}")

lj_script = """
# 1) Initialization
units lj
dimension 3
atom_style atomic
boundary p p p
# 2) System definition --> read data to continue simulation
pair_style lj/cut 4.0
read_data improved.min.data
region cyl_in cylinder z 0 0 10 INF INF side in
region cyl_out cylinder z 0 0 10 INF INF side out
group grp_t1 type 1
group grp_t2 type 2
group grp_in region cyl_in
group grp_out region cyl_out
group grp_t1_in intersect grp_t1 grp_in
group grp_t2_out intersect grp_t2 grp_out
delete_atoms group grp_t1_in
delete_atoms group grp_t2_out
# delete no longer needed groups
group grp_in delete
group grp_out delete
group grp_t1_in delete
group grp_t2_out delete
variable n1_in equal count(grp_t1,cyl_in)
variable n2_in equal count(grp_t2,cyl_in)
compute coor12 grp_t1 coord/atom cutoff 2 group grp_t2
compute sumcoor12 grp_t1 reduce ave c_coor12

# 3) Settings - No need taken from .data file 

# 4) Monitoring
thermo 1000
thermo_style custom step temp pe ke etotal press v_n1_in v_n2_in c_sumcoor12
dump viz all image 100000 lj_fluid_restart-*.ppm type type shiny 0.1 box no 0.01 view 0 0 zoom 1.8 fsaa yes size 800 800
dump_modify viz adiam 1 1 adiam 2 3 acolor 1 turquoise acolor 2 royalblue backcolor white
# 5) Run
velocity all create 1.0 49284 mom yes dist gaussian
fix mynve all nve
fix mylgv all langevin 1.0 1.0 0.1 10917 zero yes
timestep 0.005
run 300000
"""

# Execute the commands line-by-line and time it
start_time = time.time()
lmp.commands_string(lj_script)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"\n{'='*60}")
print(f"LAMMPS Calculation Time: {elapsed_time:.4f} seconds ({elapsed_time/60:.2f} minutes)")
print(f"{'='*60}\n")

# lmp.finalize() explicitly calls MPI_Finalize() before shutting down LAMMPS
lmp.finalize()
# Find all PPM images generated by your dump command
ppm_files = glob.glob("lj_fluid_restart-*.ppm")

if ppm_files:
    print(f"Converting {len(ppm_files)} PPM images to PNG...")

    for ppm_file in ppm_files:
        png_file = ppm_file.replace(".ppm", ".png")

        # Convert and save
        with Image.open(ppm_file) as img:
            img.save(png_file, "PNG")

        # Delete the uncompressed PPM original
        os.remove(ppm_file)

    print("Image conversion complete.")
#--------------------------------------------------------------------------------------------------------------
#                                   Post processing
#--------------------------------------------------------------------------------------------------------------

# Reads the log file. If you have multiple 'run' or 'minimize' commands,
# it stores them as separate blocks.
log = lammps_logfile.File("log.lj_restart")

# Get data from the first run/minimize block
step = log.get("Step", run_num=0)
v_n1 = log.get("v_n1_in", run_num=0)
v_n2 = log.get("v_n2_in", run_num=0)
c_sumcoor12 = log.get("c_sumcoor12", run_num=0)


# 4. Plot the Data in 2x2 layout
plt.figure(figsize=(8, 3))

# Top-left: Minimization Kinetic Energy
plt.subplot(1, 2, 1)
plt.plot(step/100, v_n1, color='red', linewidth=1.5, label='$N_{1,in}$')
plt.plot(step/100, v_n2, color='blue', linewidth=1.5, label='$N_{2,in}$')
plt.title('Number of Atoms in Cylinder')
plt.xlabel('$t$ / ps')
plt.ylabel('Number of Atoms')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()

# Top-right: Minimization Potential Energy
plt.subplot(1, 2, 2)
plt.plot(step/100, c_sumcoor12*100, color='orange', linewidth=1.5)
plt.title('Factor of mixing of Atoms')
plt.xlabel('$t$ / ps')
plt.ylabel('$C_{1_2}$x100')
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()


