function src = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T, X, Y, Z] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [T, X, Y, Z] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [t, x, y, z] = importfile("T:\Cloud\MATLAB iodine\MartiPiNotes\impurities_dynamics\impurities_dynamics\aimp.I_1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jun-2025 06:26:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["t", "x", "y", "z", "Var5"];
opts.SelectedVariableNames = ["t", "x", "y", "z"];
opts.VariableTypes = ["string", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["t", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["t", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
t = tbl.t;
x = tbl.x;
y = tbl.y;
z = tbl.z;

src.t = double(t);
src.vec = [double(x), double(y),double(z)] ;

end